[ScalabilityGroups]
sg.ResolutionQuality=100
sg.ViewDistanceQuality=4
sg.AntiAliasingQuality=4
sg.ShadowQuality=4
sg.PostProcessQuality=4
sg.TextureQuality=4
sg.EffectsQuality=4
sg.FoliageQuality=4
sg.ShadingQuality=4
sg.ReflectionQuality=4
sg.GlobalIlluminationQuality=4

[/Script/Engine.Engine]
bUseFixedFrameRate=False

[/Script/Engine.GameUserSettings]
bUseDynamicResolution=False
bUseVSync=False

[ScalabilitySettings]
; Unrealning avto skalasini o‘chiradi
PerfIndexValues_ResolutionQuality=100
PerfIndexValues_ViewDistanceQuality=4
PerfIndexValues_AntiAliasingQuality=4
PerfIndexValues_ShadowQuality=4
PerfIndexValues_PostProcessQuality=4
PerfIndexValues_TextureQuality=4
PerfIndexValues_EffectsQuality=4
PerfIndexValues_FoliageQuality=4
PerfIndexValues_ShadingQuality=4



[/Script/EngineSettings.GeneralProjectSettings]
r.MaterialQualityLevel=3
