[ScalabilityGroups]
sg.ResolutionQuality=100
sg.ViewDistanceQuality=3
sg.AntiAliasingQuality=4
sg.ShadowQuality=3
sg.PostProcessQuality=3
sg.TextureQuality=4
sg.EffectsQuality=3
sg.FoliageQuality=3
sg.ShadingQuality=4
sg.ReflectionQuality=4
sg.GlobalIlluminationQuality=4

[/Script/Engine.Engine]
bUseFixedFrameRate=False

[/Script/Engine.GameUserSettings]
bUseDynamicResolution=False
bUseVSync=True

[ScalabilitySettings]
; Unrealning avto skalasini o‘chiradi
PerfIndexValues_ResolutionQuality=100
PerfIndexValues_ViewDistanceQuality=3
PerfIndexValues_AntiAliasingQuality=3
PerfIndexValues_ShadowQuality=3
PerfIndexValues_PostProcessQuality=3
PerfIndexValues_TextureQuality=3
PerfIndexValues_EffectsQuality=3
PerfIndexValues_FoliageQuality=3
PerfIndexValues_ShadingQuality=3



[/Script/EngineSettings.GeneralProjectSettings]
r.MaterialQualityLevel=3