[/Script/Engine.DeviceProfileManager]
+DeviceProfiles=Windows
+DeviceProfiles=WindowsEditor
+DeviceProfiles=WindowsNoEditor
+DeviceProfiles=WindowsServer

[Windows DeviceProfile]
BaseProfileName=
DeviceType=PC
bIsDefaultProfile=False        ; ⚡ Oldingi True o‘rniga False — endi har OpenLevelda qayta yuklanmaydi
bDeviceProfileOverride=False   ; ⚡ Unreal faqat birinchi ishga tushganda qo‘llaydi

CVars=r.DefaultFeature.Bloom=1
CVars=r.DefaultFeature.AntiAliasing=2
CVars=r.AntiAliasingMethod=2
CVars=r.DefaultFeature.MotionBlur=0
CVars=r.DefaultFeature.AmbientOcclusion=1
CVars=r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=True
CVars=r.DefaultFeature.AutoExposure.Method=1
CVars=r.DefaultFeature.LumenReflections=1
CVars=r.Lumen.Reflections.HardwareRayTracing=1
CVars=r.Lumen.Reflections.ScreenTraces=1
CVars=r.Lumen.DiffuseIndirect=1
CVars=r.Lumen.Reflections.MaxRoughness=1
CVars=r.LumenSceneDetail=1
CVars=r.LumenSceneLightingQuality=1
CVars=r.LumenSceneViewDistance=20000
CVars=r.Shadow.Virtual.Enable=1
CVars=r.Shadow.Virtual.OnePassProjection.MaxLightsPerPixel=32
CVars=r.Shadow.Virtual.MaxPhysicalPages=8192
CVars=r.Shadow.CSM.MaxCascades=4
CVars=r.Shadow.MaxResolution=2048
CVars=r.SSGI.Quality=4
CVars=r.SSR.Quality=4
CVars=r.SSR.Temporal=1
CVars=r.TemporalAA.Upsampling=1
CVars=r.ViewDistanceScale=1.0
CVars=r.SkeletalMeshLODBias=0
CVars=r.StaticMeshLODDistanceScale=1.0
CVars=r.Streaming.PoolSize=12288
CVars=r.ReflectionCaptureResolution=2048
CVars=r.RayTracing=True
CVars=r.RayTracing.Shadows=True
CVars=r.RayTracing.Skylight=True
CVars=r.AllowOcclusionQueries=True
CVars=r.Nanite.AllowTessellation=True
CVars=r.Nanite.Streaming.NumInitialRootPages=8192
CVars=r.Nanite.MaxPixelsPerEdge=2
CVars=r.LumenReflections.SampleCount=128
CVars=r.Lumen.TranslucencyReflections=1
CVars=r.GenerateMeshDistanceFields=True
CVars=r.DistanceFields.DefaultVoxelDensity=0.6
CVars=r.DefaultFeature.LightUnits=1
CVars=r.ReflectionMethod=1
CVars=r.DynamicGlobalIlluminationMethod=1
CVars=r.RayTracing.GlobalIllumination=False
CVars=r.RayTracing.Reflections=False
CVars=r.LumenSceneLightingUpdateSpeed=1
CVars=r.Fog=1
CVars=r.FogDensity=0.02
CVars=r.VolumetricFog=1
CVars=r.VolumetricFog.GridPixelSize=16
CVars=r.VolumetricFog.HistoryWeight=0.9
CVars=r.TranslucencyLightingVolumeDim=64
CVars=r.SSS.Quality=1
CVars=r.EyeAdaptationQuality=2
CVars=r.Tonemapper.Sharpen=1.5
CVars=r.Tonemapper.Quality=5
CVars=r.TonemapperFilm=1
CVars=r.MipMapLODBias=0

; Epic quality defaults
CVars=r.MaterialQualityLevel=3
CVars=sg.ViewDistanceQuality=3
CVars=sg.AntiAliasingQuality=3
CVars=sg.ShadowQuality=3
CVars=sg.PostProcessQuality=3
CVars=sg.TextureQuality=3
CVars=sg.EffectsQuality=3
CVars=sg.FoliageQuality=3
CVars=sg.ShadingQuality=3
